### ISSUE TITLE
Tìm hiểu về đề tài

### ISSUE THREAD

**Issue by DuongViKhang** [DuongViKhang/TOEN430979_API-Dashboard#11]
- [x] Tiến hành tìm hiểu về API.(Day1)

 

- [x] Tiến hành tìm hiểu cách API hoạt động(Day1,2)

 

- [x] Tìm hiểu dữ liệu lấy từ API(Day2)

 

- [x] Tìm hiểu các chức năng cơ bản có thể thêm cho đề tài(Day3)

**Comment by DuongViKhang** [comment]
API hoạt động theo 4 cách khác nhau, tùy vào thời điểm và lý do chúng được tạo ra.

API SOAP
Các API này sử dụng Giao thức truy cập đối tượng đơn giản. Máy chủ và máy khách trao đổi thông điệp bằng XML. Đây là loại API kém linh hoạt được dùng phổ biến trước đây.

API RPC
Những API này được gọi là Lệnh gọi thủ tục từ xa. Máy khách hoàn thành một hàm (hoặc thủ tục) trên máy chủ còn máy chủ gửi kết quả về cho máy khách.

API Websocket
API Websocket là một bản phát triển API web hiện đại khác sử dụng các đối tượng JSON để chuyển dữ liệu. API WebSocket hỗ trợ hoạt động giao tiếp hai chiều giữa ứng dụng máy khách và máy chủ. Máy chủ có thể gửi thông điệp gọi lại cho các máy khách được kết nối, điều này khiến loại API này hiệu quả hơn API REST.

API REST
Đây là loại API phổ biến và linh hoạt nhất trên web hiện nay. Máy khách gửi yêu cầu đến máy chủ dưới dạng dữ liệu. Máy chủ dùng dữ liệu đầu vào từ máy khách này để bắt đầu các hàm nội bộ và trả lại dữ liệu đầu ra cho máy khách.

**Comment by DuongViKhang** [comment]
Link tài liệu: https://docs.google.com/document/d/1L9iCwl-rDI5lcmUT0zARBzD553mksKIChk2AaHpiNv4/edit?usp=sharing

**Comment by NguyeThanhLoi** [comment]
Link tài liệu: https://docs.google.com/document/d/10Bs8pcqKx5nJjxb4vrQT5Dif7T7QDM-VYoQjckpo1IY/edit?usp=sharing
