### ISSUE TITLE
Setup code/framework

### ISSUE THREAD

**Issue by DuongViKhang** [DuongViKhang/TOEN430979_API-Dashboard#12]
- [x] Cài đặt IDE(Day3)

 

- [x] Lựa chọn ngôn ngữ(Day4)

 

- [x] Cài đặt các thư viện cần thiết(Day5)

- [x] Cài đặt code và chạy thử(Day6,7)

 

- [x] Cài môi trường ảo (Day4)

 

- [x] Cài framework django(Day5,6)

**Comment by DuongViKhang** [comment]
Link tài liệu: https://docs.google.com/document/d/1L9iCwl-rDI5lcmUT0zARBzD553mksKIChk2AaHpiNv4/edit?usp=sharing

**Comment by NguyeThanhLoi** [comment]
Đã cài đặt môi trường ảo virtualenv
Đã cài đặt framework django
Đã chuyển dữ liệu thử
Link tài liệu đã làm: https://docs.google.com/document/d/10Bs8pcqKx5nJjxb4vrQT5Dif7T7QDM-VYoQjckpo1IY/edit?usp=sharing
