### ISSUE TITLE
Tìm hiểu về virtualization

### ISSUE THREAD

**Issue by NguyeThanhLoi** [DuongViKhang/TOEN430979_API-Dashboard#63]

**Comment by DuongViKhang** [comment]
Đã hoàn thành: https://docs.google.com/document/d/1YhQGoqPdZAHyhB6XgISjBFtrEZf6j1dZuscDHPT6-yk/edit?usp=sharing

**Comment by NguyeThanhLoi** [comment]
Link tài liệu: https://docs.google.com/document/d/1fGmlEuEyaoxmHen3vMdOAlrcfddcrhzz5z4M75djvBc/edit?usp=sharing
